BladeBlazorASP/Models/Admin.cs
namespace BladeBlazorASP.Models
{
    public class Admin
    {
        public Guid AdminID { get; set; }
        public string AdminUserName{ get; set; }
        public string AdminPassword { get; set; }
        public Admin(string adminUserName,string adminPassword)
        {
            AdminID = Guid.NewGuid();
            AdminUserName = adminUserName;
            AdminPassword = adminPassword;
        }
    }
}

BladeBlazorASP/Models/EmailSubscribers.cs
using System.ComponentModel.DataAnnotations;

namespace BladeBlazorASP.Models
{
    public class EmailSubscribers
    {
        [Key]
        public Guid SubscriberID { get; set; }
        [Required]
        public string EmailAddress { get; set; }
        public bool IsSubscriber{ get; set; }=true;
        public EmailSubscribers()
        {
            
        }

        public EmailSubscribers( string emailAddress)
        {
            SubscriberID = Guid.NewGuid(); 
            EmailAddress = emailAddress;
            IsSubscriber = true;                    
        }

    }
}

BladeBlazorASP/Models/ErrorViewModel.cs
namespace BladeBlazorASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BladeBlazorASP/Models/Project.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BladeBlazorASP.Models
{
    public class Project
    {
        [Key]
        public int ProjectId { get; set; }

        [DisplayName("Project Name")]
        public string ProjectName { get; set; }
        [DisplayName("Project Image")]
        public string ProjectImg { get; set; }
        [DisplayName("Project Description")]
        public string ProjectDescription { get; set; }
        public Project()
        {
            
        }
        public Project( string projectName,string projectImg,string projectDescription)
        {
            ProjectName = projectName;
            ProjectImg = projectImg;
            ProjectDescription = projectDescription;
            
        }
    }
}

BladeBlazorASP/Models/SendEmail.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;

namespace BladeBlazorASP.Models
{
    public class SendEmail
    {
        [ValidateNever]
        public string FromEmail{ get; set; }

        [DisplayName("To:")]
        public string ToEmail{ get; set; }

        [DisplayName("Subject:")]
        public string Subject{ get; set; }

        [DisplayName("Message:")]
        public string EmailMessageBody { get; set; }

        [DisplayName("Attach File:")]
        [ValidateNever]
        public string ? EmailAttachmentUrl { get; set; }
    }
}

BladeBlazorASP/Controllers/EmailSubscribersController.cs
using BladeBlazorASP.Data;
using BladeBlazorASP.Models;
using Microsoft.AspNetCore.Mvc;

namespace BladeBlazorASP.Controllers
{
    public class EmailSubscribersController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        public EmailSubscribersController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
            
        }
        public IActionResult Index()
        {   
            var emailSubscribersList=_applicationDbContext.EmailSubscribers.ToList();
            return View(emailSubscribersList);
        }
       
    }
}

BladeBlazorASP/Controllers/HomeController.cs
using BladeBlazorASP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net;
using System.Net.Mail;

namespace BladeBlazorASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SendEmail( SendEmail email,IFormFile AttachedFile)
        {
            var myAppConfig = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            var Username=myAppConfig.GetValue<string>("EmailConfigurationSettings:Username");
            var Password=myAppConfig.GetValue<string>("EmailConfigurationSettings:Password");
            var Host=myAppConfig.GetValue<string>("EmailConfigurationSettings:Host");
            var Port=myAppConfig.GetValue<int>("EmailConfigurationSettings:Port");
            var FromEmail= myAppConfig.GetValue<string>("EmailConfigurationSettings:FromEmail");

            MailMessage message= new MailMessage();
            message.From=new MailAddress(FromEmail);
            message.To.Add(email.ToEmail.ToString());
            message.Subject=email.Subject;
            message.IsBodyHtml = true;
            message.Body = email.EmailMessageBody;
            message.Attachments.Add(new Attachment(AttachedFile.OpenReadStream(), AttachedFile.FileName));

            SmtpClient mailClient = new SmtpClient(Host);
             mailClient.Credentials=new System.Net.NetworkCredential(Username,Password);
            try
            {
                 mailClient.UseDefaultCredentials = true;
                 mailClient.Host = Host;
                 mailClient.Port=Port;
               //  mailClient.EnableSsl =true;
                 mailClient.Send(message);

            }
            catch (Exception ex)   
            {

                throw;
            }
            finally
            {
                mailClient.Dispose();
            }



            return View("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BladeBlazorASP/Controllers/ProjectsController.cs
using BladeBlazorASP.Data;
using BladeBlazorASP.Models;
using Microsoft.AspNetCore.Mvc;

namespace BladeBlazorASP.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProjectsController(ApplicationDbContext applicationDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _applicationDbContext = applicationDbContext;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddNewProject()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddNewProject(Project project, IFormFile? file)
        {
           

                string wwwRootPath = _webHostEnvironment.WebRootPath;

                if(file is not null)
                {
                    string fileName=Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string projectPath=Path.Combine(wwwRootPath,@"images\projects");
                    using (var fileStream = new FileStream(Path.Combine(projectPath,fileName),FileMode.Create))
                    {
                        file.CopyTo(fileStream);

                    }
                    project.ProjectImg = @"\images\projects\" + fileName;

                }
               
                _applicationDbContext.Projects.Add(project);
                _applicationDbContext.SaveChanges();
                TempData["success"] = "Project created successfully";


            
            return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult Index(EmailSubscribers emailSubscriber)
        {

            _applicationDbContext.EmailSubscribers.Add(emailSubscriber);
            _applicationDbContext.SaveChanges();
            TempData["success"] = "Your Have Successfully Subscribed to Our News Letters";
            return View();
        }
    }
}

BladeBlazorASP/Views/EmailSubscribers/Index.cshtml
@model List<EmailSubscribers>
<h1>Email Subscribers</h1>
<table class="table table-bordered table-striped">
<thead>
        <tr>

            <th>Email Addresses</th>
            <th>Subscribed</th>

        </tr>

</thead>

  <tbody>
        @foreach(var emailDomain in Model)
        {
            <tr>

                <td>@emailDomain.EmailAddress</td>
                <td>@emailDomain.IsSubscriber</td>

            </tr>
        }

  </tbody>


</table>

BladeBlazorASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model SendEmail

<div class=" container-sm p-0"> 
    <div class="row flex-sm-row justify-content-sm-end p-1">
        <a asp-controller="Projects" asp-action="AddNewProject">
            <button class="add-projects btn-sm btn-dark text-light p-1">Add Project</button>
        </a>
       
    </div>

</div>

<div class="container d-flex flex-column align-items-center justify-content-center">
    <h1 class="display-4">Welcome</h1>
    <p>Admin</p>
    <div class="admin-img bg-dark text-light d-flex align-items-center justify-content-center">
        Stanley Oduor
    </div>

</div>
<form method="post" enctype="multipart/form-data" asp-action="SendEmail">
    <div class="mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Add News Letters</h2>
            <hr />
        </div>

        <div class="row mb-3 p-1">
            <label asp-for="ToEmail" class="p-0"></label>
            <input asp-for="ToEmail" class="form-control" />

        </div>
        <div class="row mb-3 p-1">
            <label asp-for="Subject" class="p-0"></label>
            <input asp-for="Subject" class="form-control" />

        </div>
        <div class="row mb-3 p-1">
            <label asp-for="EmailMessageBody" class="p-0"></label>
            <textarea asp-for="EmailMessageBody" class="form-control" rows="5" cols="20"></textarea>

        </div>
        <div class="row mb-3 p-1">
            <label asp-for="EmailAttachmentUrl" class="p-0"></label>
            <input asp-for="EmailAttachmentUrl" type="file" name="AttachedFile" class="form-control" />

        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-dark form-control">Send Email</button>

            </div>
           
        </div>

    </div>
</form>

BladeBlazorASP/Views/Projects/AddNewProject.cshtml
@model Project
<form method="post" enctype="multipart/form-data">
    <div class="mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Add New Project</h2>
            <hr/>
        </div>
        <div class="row mb-3 p-1"> 
            <label asp-for="ProjectName" class="p-0"></label>
            <input asp-for="ProjectName" class="form-control" />

        </div>
        <div class="row mb-3 p-1"> 
            <label asp-for="ProjectDescription" class="p-0"></label>
            <input asp-for="ProjectDescription" class="form-control" />

        </div>
        <div class="row mb-3 p-1"> 
            <label asp-for="ProjectImg" class="p-0"></label>
            <input type="file" name="file" class="form-control"/>

        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-dark form-control">Add</button>

            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Projects" asp-action="Index" class="btn btn-outline-dark border form-control">View Projects </a>

            </div>

        </div>

    </div>
</form>

BladeBlazorASP/Views/Projects/Index.cshtml
@model EmailSubscribers


<div class="row"><div class="col-6"><h1>Upcoming Projects</h1></div></div>
<hr/>
<partial name="_Notification"/>
<div class="container bg-dark text-light p-1">
    <div class="row project-section d-sm-flex flex-sm-row flex-sm-wrap align-items-center justify-content-evenly">
        <div class="col-sm-5 my-3 project-card"><img 
            src="\wwwroot\images\projects\70c8ef93-a157-4a5c-8613-ffbd2c619408.png"/></div>
    </div>
    <div>
        <form method="post">
          <div class="p-5 my-4 rounded-3 p-5 bg-light text-dark">
              <div class="row pb-2 flex-sm-column align-items-center justify-content-center">
                  
                  <div class="col-6"> <h3>Subscribe to Our News Letters</h3></div>
                  <div class="col-6"><hr/></div>          
              </div>
              <div class="row pb-2 flex-sm-row align-items-center justify-content-center">

                    <div class="col-sm-6 flex-row justify-content-center">
                        <div class="row">
                            <input type="email" asp-for="EmailAddress" class="input-box form-control-sm w-75 text-opacity-75 p-2" placeholder="Enter Your Email Address" />
                            <button type="submit" class="btn-sm btn-dark text-light form-control-sm w-25 p-1 mb-0 border-0 btn-outline-success">Subscribe Now</button>
                        </div>
                       
                    </div>

               </div>
          
          </div>

        </form>
    </div>
    
</div>

BladeBlazorASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BladeBlazorASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BladeBlazorASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BladeBlazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="EmailSubscribers" asp-action="Index">Subscribers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BladeBlazor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BladeBlazorASP/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <h5 class="text-success"> @TempData["success"]</h5>
}